# Generated by Django 4.2.30 on 2026-06-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_agenda', models.CharField(default='Minha Agenda', max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_padrao_evento', models.PositiveIntegerField(default=30, verbose_name='Tempo padrão (min)')),
                ('intervalo_entre_eventos', models.PositiveIntegerField(default=0, verbose_name='Intervalo (min)')),
                ('horario_inicio', models.TimeField(default='08:00', verbose_name='Horário inicial')),
                ('horario_fim', models.TimeField(default='18:00', verbose_name='Horário final')),
                ('dias_trabalho', models.CharField(default='1,2,3,4,5', help_text='0=Dom, 1=Seg, ..., 6=Sáb. Separar por vírgula.', max_length=20, verbose_name='Dias de trabalho')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('cor_primaria', models.CharField(default='#111827', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração da Agenda',
                'verbose_name_plural': 'Configurações da Agenda',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('auditoria', 'Auditoria'), ('consultoria', 'Consultoria'), ('treinamento', 'Treinamento'), ('outro', 'Outro')], default='reuniao', max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data e Hora de Término')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local/Link')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('duracao_minutos', models.PositiveIntegerField(default=30, verbose_name='Duração (minutos)')),
                ('cor', models.CharField(default='#111827', help_text='Cor em hexadecimal (ex: #111827)', max_length=7, verbose_name='Cor')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
