# Generated by Django 4.2.30 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoAgenda',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='duracao_minutos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='evento',
            name='cor',
            field=models.CharField(default='#6366f1', help_text='Cor em hexadecimal (ex: #6366f1)', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
    ]
