# Generated by Django 4.2.30 on 2026-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_delete_configuracaoagenda_remove_evento_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Geral'), ('consulta', 'Consulta'), ('trabalho', 'Trabalho'), ('pessoal', 'Pessoal'), ('urgente', 'Urgente')], default='geral', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_limite_recorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Repetir até'),
        ),
        migrations.AddField(
            model_name='evento',
            name='serie_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Série'),
        ),
    ]
